### ISSUE TITLE
Numbered lists are not properly converted

### ISSUE THREAD

**Issue by bisherbas** [mwilliamson/mammoth-wordpress-plugin#4]
Example .docx content with numbered list:

```
1) item 1
some text
some text
2) item 2
3) item 3
some text
4) item 4

```
Converted into:
```
1. item 1
some text
some text
1. item 2
1. item 3
some text
1. item 4
```

WordPress 4.9.2
PHP 7.0.25

**Comment by mwilliamson** [comment]
Could you provide an example document, the HTML you'd expect, and the HTML that's being generated? Thanks.

**Comment by bisherbas** [comment]
[test file.docx](https://github.com/mwilliamson/mammoth-wordpress-plugin/files/1692060/test.file.docx)

[text file html.txt](https://github.com/mwilliamson/mammoth-wordpress-plugin/files/1692061/text.file.html.txt)

**Comment by mwilliamson** [comment]
I don't have a copy of Word to hand right now, but from opening the document in LibreOffice, it looks to me as though all of the list items are top-level items. Although the bullets are visually indented further than the numbered items, LibreOffice thinks that they're at the same level as the numbered items since both cannot have their indentation decreased. If you want Mammoth to treat the bullets as children of the numbered items, then they'll need to be represented in the original document as level 2 list items.

**Comment by bisherbas** [comment]
![image](https://user-images.githubusercontent.com/7196815/36006526-74be1dda-0d0b-11e8-9ca2-9be684fcdbe7.jpg)

You can see how it looks in Word 2016. I am merely sharing my experience with Mammoth. If you do not consider this behavior as bug, go ahead and close the ticket. Otherwise, I do not have any further requests. Thanks for your time.

**Comment by mwilliamson** [comment]
Thanks for the screenshot. As I said, Mammoth is just copying the structure of the document, so you'll need to update your original document to have nested lists if you want that reflected in the output. This is intentional, so I'm closing the issue.
