### ISSUE TITLE
Space characters on new lines breaking <pre> blocks

### ISSUE THREAD

**Issue by DaveConvery** [mwilliamson/mammoth-wordpress-plugin#7]
The HTML conversion inserts 2 space characters as a tab on each new line, which is great for legibility, but in code blocks it's breaking Python code when you copy it out. Would it be possibly to (perhaps optionally) switch this off when it's in code, so additional spaces aren't displayed in the rendered `<pre>`?

Sorry.

Also: hi!

**Comment by mwilliamson** [comment]
Hello!

Hmm, that might be because of the pretty printing of the HTML -- are there are any `div`, `p`, `ul` or `li` tags inside the `pre`?

If you're still using a plugin to pass custom options to Mammoth, then you can tweak it to disable the pretty printing by changing the return value of `MAMMOTH_OPTIONS` to include `prettyPrint: false`. For instance, instead of:

```javascript
    return {
        styleMap: styleMap,
        transformDocument: ...
    };
```

you'd have:

```javascript
    return {
        prettyPrint: false,
        styleMap: styleMap,
        transformDocument: ...
    };
```

That'll completely turn off the pretty printing, which might not be what you want, but you can see whether that's the cause of the issue. If it is, then the more sensible fix would be for Mammoth to disable pretty printing inside `<pre>` elements.

If you have an example document, that'd be handy to look at.

**Comment by DaveConvery** [comment]
This is a recent doc that we've run the importer on:

[stPython5_KK_FINAL.docx](https://github.com/mwilliamson/mammoth-wordpress-plugin/files/1830891/stPython5_KK_FINAL.docx)

This is a recent doc that we used - the `<pre>` appears to be as it should be. We're not prettyprinting - code is coloured by Crayon but the spaces are there in code copied out of the raw HTML immediately after import (see image)

<img width="756" alt="screenshot 2018-03-20 19 30 02" src="https://user-images.githubusercontent.com/1324433/37678277-7b0d074e-2c75-11e8-837b-7c3f8bc9bdb6.png">

**Comment by mwilliamson** [comment]
Sorry, I probably wasn't very clear about the pretty printing: the Mammoth plugin itself will, by default, pretty print the output. If it wasn't pretty printing, if memory serves, you'd get the HTML all on one line, apart from the newlines in the `<pre>`.

**Comment by DaveConvery** [comment]
Ah, I get you. I'll test that out. Thanks!

**Comment by mwilliamson** [comment]
Did you manage to get this sorted?

**Comment by DaveConvery** [comment]
I submitted a pull request, but the staging environment has been broken for... a while. It is Schrodinger's fix.

**Comment by DaveConvery** [comment]
I was finally able to test this, and it doesn't seem to have worked. The rerun value is:
![mammoth_options](https://user-images.githubusercontent.com/1324433/39922360-acbcf3e8-5516-11e8-8fd5-07a2988c3ed2.png)

But it doesn't seem to have disabled prettyprinting at all.

**Comment by mwilliamson** [comment]
Hmm, it seemed to work when I tried it out, so I'm not sure what's happening there. Perhaps a caching issue: did you try it out in a private browsing window?

In any case, 1.9.0 has been released, which should hopefully have a fix for the issue without having to disable pretty printing.

**Comment by DaveConvery** [comment]
It works beautifully, you absolute star.

**Comment by mwilliamson** [comment]
Marvellous!
